// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: proto/payment.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "payment";

export interface CreateWalletRequest {
  userId: string;
  currency: string;
}

export interface CreateWalletResponse {
  success: boolean;
  message: string;
  error: string;
  data: WalletData | undefined;
}

export interface GetWalletRequest {
  userId: string;
  walletId: string;
}

export interface GetWalletResponse {
  success: boolean;
  message: string;
  error: string;
  data: WalletData | undefined;
}

export interface UpdateWalletRequest {
  walletId: string;
  userId: string;
  balance: number;
}

export interface UpdateWalletResponse {
  success: boolean;
  message: string;
  error: string;
  data: WalletData | undefined;
}

export interface CreateTransferRequest {
  fromUserId: string;
  toUserId: string;
  amount: number;
  currency: string;
  description: string;
}

export interface CreateTransferResponse {
  success: boolean;
  message: string;
  error: string;
  data: TransactionData | undefined;
}

export interface GetTransactionsRequest {
  userId: string;
  page: number;
  limit: number;
}

export interface GetTransactionsResponse {
  success: boolean;
  message: string;
  error: string;
  data: TransactionData[];
  total: number;
}

export interface GetTransactionRequest {
  transactionId: string;
  userId: string;
}

export interface GetTransactionResponse {
  success: boolean;
  message: string;
  error: string;
  data: TransactionData | undefined;
}

export interface WalletData {
  id: string;
  userId: string;
  balance: number;
  currency: string;
  createdAt: string;
  updatedAt: string;
}

export interface TransactionData {
  id: string;
  fromUserId: string;
  toUserId: string;
  amount: number;
  currency: string;
  status: string;
  type: string;
  description: string;
  createdAt: string;
  updatedAt: string;
}

export const PAYMENT_PACKAGE_NAME = "payment";

export interface PaymentServiceClient {
  createWallet(request: CreateWalletRequest, metadata?: Metadata): Observable<CreateWalletResponse>;

  getWallet(request: GetWalletRequest, metadata?: Metadata): Observable<GetWalletResponse>;

  updateWallet(request: UpdateWalletRequest, metadata?: Metadata): Observable<UpdateWalletResponse>;

  createTransfer(request: CreateTransferRequest, metadata?: Metadata): Observable<CreateTransferResponse>;

  getTransactions(request: GetTransactionsRequest, metadata?: Metadata): Observable<GetTransactionsResponse>;

  getTransaction(request: GetTransactionRequest, metadata?: Metadata): Observable<GetTransactionResponse>;
}

export interface PaymentServiceController {
  createWallet(
    request: CreateWalletRequest,
    metadata?: Metadata,
  ): Promise<CreateWalletResponse> | Observable<CreateWalletResponse> | CreateWalletResponse;

  getWallet(
    request: GetWalletRequest,
    metadata?: Metadata,
  ): Promise<GetWalletResponse> | Observable<GetWalletResponse> | GetWalletResponse;

  updateWallet(
    request: UpdateWalletRequest,
    metadata?: Metadata,
  ): Promise<UpdateWalletResponse> | Observable<UpdateWalletResponse> | UpdateWalletResponse;

  createTransfer(
    request: CreateTransferRequest,
    metadata?: Metadata,
  ): Promise<CreateTransferResponse> | Observable<CreateTransferResponse> | CreateTransferResponse;

  getTransactions(
    request: GetTransactionsRequest,
    metadata?: Metadata,
  ): Promise<GetTransactionsResponse> | Observable<GetTransactionsResponse> | GetTransactionsResponse;

  getTransaction(
    request: GetTransactionRequest,
    metadata?: Metadata,
  ): Promise<GetTransactionResponse> | Observable<GetTransactionResponse> | GetTransactionResponse;
}

export function PaymentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createWallet",
      "getWallet",
      "updateWallet",
      "createTransfer",
      "getTransactions",
      "getTransaction",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PaymentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PaymentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PAYMENT_SERVICE_NAME = "PaymentService";
