// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: proto/dispute.proto

package dispute

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DisputeServiceClient is the client API for DisputeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DisputeServiceClient interface {
	CreateDispute(ctx context.Context, in *CreateDisputeRequest, opts ...grpc.CallOption) (*CreateDisputeResponse, error)
	GetDispute(ctx context.Context, in *GetDisputeRequest, opts ...grpc.CallOption) (*GetDisputeResponse, error)
	GetDisputes(ctx context.Context, in *GetDisputesRequest, opts ...grpc.CallOption) (*GetDisputesResponse, error)
	UpdateDispute(ctx context.Context, in *UpdateDisputeRequest, opts ...grpc.CallOption) (*UpdateDisputeResponse, error)
	ResolveDispute(ctx context.Context, in *ResolveDisputeRequest, opts ...grpc.CallOption) (*ResolveDisputeResponse, error)
}

type disputeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDisputeServiceClient(cc grpc.ClientConnInterface) DisputeServiceClient {
	return &disputeServiceClient{cc}
}

func (c *disputeServiceClient) CreateDispute(ctx context.Context, in *CreateDisputeRequest, opts ...grpc.CallOption) (*CreateDisputeResponse, error) {
	out := new(CreateDisputeResponse)
	err := c.cc.Invoke(ctx, "/dispute.DisputeService/CreateDispute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *disputeServiceClient) GetDispute(ctx context.Context, in *GetDisputeRequest, opts ...grpc.CallOption) (*GetDisputeResponse, error) {
	out := new(GetDisputeResponse)
	err := c.cc.Invoke(ctx, "/dispute.DisputeService/GetDispute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *disputeServiceClient) GetDisputes(ctx context.Context, in *GetDisputesRequest, opts ...grpc.CallOption) (*GetDisputesResponse, error) {
	out := new(GetDisputesResponse)
	err := c.cc.Invoke(ctx, "/dispute.DisputeService/GetDisputes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *disputeServiceClient) UpdateDispute(ctx context.Context, in *UpdateDisputeRequest, opts ...grpc.CallOption) (*UpdateDisputeResponse, error) {
	out := new(UpdateDisputeResponse)
	err := c.cc.Invoke(ctx, "/dispute.DisputeService/UpdateDispute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *disputeServiceClient) ResolveDispute(ctx context.Context, in *ResolveDisputeRequest, opts ...grpc.CallOption) (*ResolveDisputeResponse, error) {
	out := new(ResolveDisputeResponse)
	err := c.cc.Invoke(ctx, "/dispute.DisputeService/ResolveDispute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DisputeServiceServer is the server API for DisputeService service.
// All implementations must embed UnimplementedDisputeServiceServer
// for forward compatibility
type DisputeServiceServer interface {
	CreateDispute(context.Context, *CreateDisputeRequest) (*CreateDisputeResponse, error)
	GetDispute(context.Context, *GetDisputeRequest) (*GetDisputeResponse, error)
	GetDisputes(context.Context, *GetDisputesRequest) (*GetDisputesResponse, error)
	UpdateDispute(context.Context, *UpdateDisputeRequest) (*UpdateDisputeResponse, error)
	ResolveDispute(context.Context, *ResolveDisputeRequest) (*ResolveDisputeResponse, error)
	mustEmbedUnimplementedDisputeServiceServer()
}

// UnimplementedDisputeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDisputeServiceServer struct {
}

func (UnimplementedDisputeServiceServer) CreateDispute(context.Context, *CreateDisputeRequest) (*CreateDisputeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDispute not implemented")
}
func (UnimplementedDisputeServiceServer) GetDispute(context.Context, *GetDisputeRequest) (*GetDisputeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDispute not implemented")
}
func (UnimplementedDisputeServiceServer) GetDisputes(context.Context, *GetDisputesRequest) (*GetDisputesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDisputes not implemented")
}
func (UnimplementedDisputeServiceServer) UpdateDispute(context.Context, *UpdateDisputeRequest) (*UpdateDisputeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDispute not implemented")
}
func (UnimplementedDisputeServiceServer) ResolveDispute(context.Context, *ResolveDisputeRequest) (*ResolveDisputeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveDispute not implemented")
}
func (UnimplementedDisputeServiceServer) mustEmbedUnimplementedDisputeServiceServer() {}

// UnsafeDisputeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DisputeServiceServer will
// result in compilation errors.
type UnsafeDisputeServiceServer interface {
	mustEmbedUnimplementedDisputeServiceServer()
}

func RegisterDisputeServiceServer(s grpc.ServiceRegistrar, srv DisputeServiceServer) {
	s.RegisterService(&DisputeService_ServiceDesc, srv)
}

func _DisputeService_CreateDispute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDisputeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisputeServiceServer).CreateDispute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dispute.DisputeService/CreateDispute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisputeServiceServer).CreateDispute(ctx, req.(*CreateDisputeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DisputeService_GetDispute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDisputeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisputeServiceServer).GetDispute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dispute.DisputeService/GetDispute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisputeServiceServer).GetDispute(ctx, req.(*GetDisputeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DisputeService_GetDisputes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDisputesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisputeServiceServer).GetDisputes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dispute.DisputeService/GetDisputes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisputeServiceServer).GetDisputes(ctx, req.(*GetDisputesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DisputeService_UpdateDispute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDisputeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisputeServiceServer).UpdateDispute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dispute.DisputeService/UpdateDispute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisputeServiceServer).UpdateDispute(ctx, req.(*UpdateDisputeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DisputeService_ResolveDispute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveDisputeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisputeServiceServer).ResolveDispute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dispute.DisputeService/ResolveDispute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisputeServiceServer).ResolveDispute(ctx, req.(*ResolveDisputeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DisputeService_ServiceDesc is the grpc.ServiceDesc for DisputeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DisputeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dispute.DisputeService",
	HandlerType: (*DisputeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDispute",
			Handler:    _DisputeService_CreateDispute_Handler,
		},
		{
			MethodName: "GetDispute",
			Handler:    _DisputeService_GetDispute_Handler,
		},
		{
			MethodName: "GetDisputes",
			Handler:    _DisputeService_GetDisputes_Handler,
		},
		{
			MethodName: "UpdateDispute",
			Handler:    _DisputeService_UpdateDispute_Handler,
		},
		{
			MethodName: "ResolveDispute",
			Handler:    _DisputeService_ResolveDispute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dispute.proto",
}
