// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: proto/contract.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "contract";

export interface CreateContractRequest {
  userId: string;
  title: string;
  description: string;
  amount: number;
  currency: string;
  clientId: string;
  freelancerId: string;
}

export interface CreateContractResponse {
  success: boolean;
  message: string;
  error: string;
  data: ContractData | undefined;
}

export interface GetContractRequest {
  contractId: string;
  userId: string;
}

export interface GetContractResponse {
  success: boolean;
  message: string;
  error: string;
  data: ContractData | undefined;
}

export interface GetContractsRequest {
  userId: string;
  page: number;
  limit: number;
}

export interface GetContractsResponse {
  success: boolean;
  message: string;
  error: string;
  data: ContractData[];
  total: number;
}

export interface UpdateContractRequest {
  contractId: string;
  userId: string;
  title: string;
  description: string;
  amount: number;
  status: string;
}

export interface UpdateContractResponse {
  success: boolean;
  message: string;
  error: string;
  data: ContractData | undefined;
}

export interface DeleteContractRequest {
  contractId: string;
  userId: string;
}

export interface DeleteContractResponse {
  success: boolean;
  message: string;
  error: string;
}

export interface ContractData {
  id: string;
  title: string;
  description: string;
  amount: number;
  currency: string;
  status: string;
  clientId: string;
  freelancerId: string;
  createdAt: string;
  updatedAt: string;
}

export const CONTRACT_PACKAGE_NAME = "contract";

export interface ContractServiceClient {
  createContract(request: CreateContractRequest, metadata?: Metadata): Observable<CreateContractResponse>;

  getContract(request: GetContractRequest, metadata?: Metadata): Observable<GetContractResponse>;

  getContracts(request: GetContractsRequest, metadata?: Metadata): Observable<GetContractsResponse>;

  updateContract(request: UpdateContractRequest, metadata?: Metadata): Observable<UpdateContractResponse>;

  deleteContract(request: DeleteContractRequest, metadata?: Metadata): Observable<DeleteContractResponse>;
}

export interface ContractServiceController {
  createContract(
    request: CreateContractRequest,
    metadata?: Metadata,
  ): Promise<CreateContractResponse> | Observable<CreateContractResponse> | CreateContractResponse;

  getContract(
    request: GetContractRequest,
    metadata?: Metadata,
  ): Promise<GetContractResponse> | Observable<GetContractResponse> | GetContractResponse;

  getContracts(
    request: GetContractsRequest,
    metadata?: Metadata,
  ): Promise<GetContractsResponse> | Observable<GetContractsResponse> | GetContractsResponse;

  updateContract(
    request: UpdateContractRequest,
    metadata?: Metadata,
  ): Promise<UpdateContractResponse> | Observable<UpdateContractResponse> | UpdateContractResponse;

  deleteContract(
    request: DeleteContractRequest,
    metadata?: Metadata,
  ): Promise<DeleteContractResponse> | Observable<DeleteContractResponse> | DeleteContractResponse;
}

export function ContractServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createContract", "getContract", "getContracts", "updateContract", "deleteContract"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ContractService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ContractService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CONTRACT_SERVICE_NAME = "ContractService";
