// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: proto/dispute.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "dispute";

export interface CreateDisputeRequest {
  userId: string;
  contractId: string;
  title: string;
  description: string;
  category: string;
}

export interface CreateDisputeResponse {
  success: boolean;
  message: string;
  error: string;
  data: DisputeData | undefined;
}

export interface GetDisputeRequest {
  disputeId: string;
  userId: string;
}

export interface GetDisputeResponse {
  success: boolean;
  message: string;
  error: string;
  data: DisputeData | undefined;
}

export interface GetDisputesRequest {
  userId: string;
  page: number;
  limit: number;
}

export interface GetDisputesResponse {
  success: boolean;
  message: string;
  error: string;
  data: DisputeData[];
  total: number;
}

export interface UpdateDisputeRequest {
  disputeId: string;
  userId: string;
  title: string;
  description: string;
  status: string;
}

export interface UpdateDisputeResponse {
  success: boolean;
  message: string;
  error: string;
  data: DisputeData | undefined;
}

export interface ResolveDisputeRequest {
  disputeId: string;
  resolverId: string;
  resolution: string;
  outcome: string;
}

export interface ResolveDisputeResponse {
  success: boolean;
  message: string;
  error: string;
  data: DisputeData | undefined;
}

export interface DisputeData {
  id: string;
  contractId: string;
  clientId: string;
  freelancerId: string;
  title: string;
  description: string;
  category: string;
  status: string;
  resolution: string;
  outcome: string;
  resolverId: string;
  createdAt: string;
  updatedAt: string;
}

export const DISPUTE_PACKAGE_NAME = "dispute";

export interface DisputeServiceClient {
  createDispute(request: CreateDisputeRequest, metadata?: Metadata): Observable<CreateDisputeResponse>;

  getDispute(request: GetDisputeRequest, metadata?: Metadata): Observable<GetDisputeResponse>;

  getDisputes(request: GetDisputesRequest, metadata?: Metadata): Observable<GetDisputesResponse>;

  updateDispute(request: UpdateDisputeRequest, metadata?: Metadata): Observable<UpdateDisputeResponse>;

  resolveDispute(request: ResolveDisputeRequest, metadata?: Metadata): Observable<ResolveDisputeResponse>;
}

export interface DisputeServiceController {
  createDispute(
    request: CreateDisputeRequest,
    metadata?: Metadata,
  ): Promise<CreateDisputeResponse> | Observable<CreateDisputeResponse> | CreateDisputeResponse;

  getDispute(
    request: GetDisputeRequest,
    metadata?: Metadata,
  ): Promise<GetDisputeResponse> | Observable<GetDisputeResponse> | GetDisputeResponse;

  getDisputes(
    request: GetDisputesRequest,
    metadata?: Metadata,
  ): Promise<GetDisputesResponse> | Observable<GetDisputesResponse> | GetDisputesResponse;

  updateDispute(
    request: UpdateDisputeRequest,
    metadata?: Metadata,
  ): Promise<UpdateDisputeResponse> | Observable<UpdateDisputeResponse> | UpdateDisputeResponse;

  resolveDispute(
    request: ResolveDisputeRequest,
    metadata?: Metadata,
  ): Promise<ResolveDisputeResponse> | Observable<ResolveDisputeResponse> | ResolveDisputeResponse;
}

export function DisputeServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createDispute", "getDispute", "getDisputes", "updateDispute", "resolveDispute"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("DisputeService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("DisputeService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const DISPUTE_SERVICE_NAME = "DisputeService";
